---
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ ad_join_apt_required_packages }}"

- name: Install pexpect Python module
  ansible.builtin.pip:
    name: pexpect
    state: present
