---
- name: Discover domain and check if SSSD is needed
  shell: /bin/bash -c "/usr/sbin/realm discover {{ ad_join_domain_name }} | grep -q sssd"
  register: ad_domain_discovery
  changed_when: false
  ignore_errors: true

- name: Configure Kerberos
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
  notify: Restart SSSD

- name: Join linux into domain
  expect:
      command: /bin/bash -c "/usr/sbin/realm join {{ ad_join_domain_name }} -U '{{ ad_join_username }}' --install=/"
      responses:
          Password.*: "{{ ad_join_password }}"

- name: Configure SSSD
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
  notify: Restart SSSD

- name: Map Active Directory Guests group
  shell: /usr/bin/net -s /dev/null groupmap add sid=S-1-5-32-546 unixgroup={{ ad_join_linux_anonymous_group_name }} type=builtin
