---
- name: Discover domain and check if SSSD is needed
  shell: /bin/bash -c "/usr/sbin/realm discover {{ ad_join_domain_name }} | grep -q sssd"
  register: ad_domain_discovery
  changed_when: false
  ignore_errors: true

- name: Join linux into domain
  expect:
      command: /bin/bash -c "/usr/sbin/realm join {{ ad_join_domain_name }} -U '{{ ad_join_username }}' --install=/"
      responses:
          Password.*: "{{ ad_join_password }}"

- name: Configure SSSD
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
  notify: Restart SSSD
