---
- name: Join Active Directory using SSSD
  ansible.builtin.import_tasks: sssd/main.yml
  when: ad_join_method == 'sssd'

- name: Join Active Directory using Winbind
  ansible.builtin.import_tasks: winbind/main.yml
  when: ad_join_method == 'winbind'
