---
- name: Check if NTPd service exist
  ansible.builtin.command: service ntpd status
  register: ntpd_service_status
  changed_when: false
  failed_when: not(ntpd_service_status.rc in [0, 3, 4])
  args:
    warn: false

- name: Ensure NTPd service is stopped
  ansible.builtin.service:
    name: ntpd
    state: stopped
    enabled: false
  when: ntpd_service_status.rc == 0

- name: Sync system date/time with AD Domain Controller
  ansible.builtin.command: ntpdate {{ ad_join_domain_name }}
  changed_when: false
  register: _timesync_result

- name: Ensure NTPd service is started
  ansible.builtin.service:
    name: ntpd
    state: started
    enabled: false
  when: ntpd_service_status.rc == 0
